name: Generate Snake Contributions
on:
  schedule:
    - cron: '0 0 * * *'  # Fixed cron syntax
  workflow_dispatch:
  push: 
    branches: ["main"]
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk/svg-only@v2  # Using the same version as the example
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#020080&color_dots=#888,#09b43a,#efb041,#ff6969,#1688f0
      # Commit the changes
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
